options {
    directory "/var/cache/bind";
    
    allow-query { any; };
    allow-transfer { none; };
    
    querylog yes;
};

zone "ghostshark.local" IN {
    type master;
    file "/etc/bind/zones/db.ghostshark.local";
};

zone "74.102.10.in-addr.arpa" IN {
    type master;
    file "/etc/bind/zones/db.10.102.74";
};

